version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - ./data/mongo_data:/data/db
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    depends_on:
      - mongodb
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb

  flask:
    build: ./flask_app
    container_name: flask
    depends_on:
      - mongodb
    ports:
      - "5000:5000"

  streamlit:
    build: ./streamlit_app
    container_name: streamlit
    depends_on:
      - flask
    ports:
      - "8501:8501"

  jupyter:
    build: ./jupyter
    container_name: jupyter
    ports:
      - "8887:8888"
    volumes:
      - ./jupyter/notebooks:/home/jovyan/work
